---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project-api-deployment
  minReplicas: 1
  maxReplicas: 40
  targetCPUUtilizationPercentage: 50
