---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lab-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lab-api-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
