---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: woojaechung
resources:
  - ../../base
  - virtual-service.yaml
  - hpa-api.yaml
  - hpa-api-project.yaml
images:
  - name: project
    newName: w255mids.azurecr.io/woojaechung/project
    newTag: "b352d58"
